export type TemplateKey = "landscaping" | "d2d" | "contractor" | "cleaning" | "pest" | "general";

export const templates: Record<TemplateKey, { label: string; description: string; modules: string[] }> = {
  landscaping: {
    label: "Landscaping",
    description: "Jobs, crews, equipment, tools, inventory, issues, photos, and yard operations.",
    modules: ["Jobs", "Crews", "Equipment", "Tools", "Inventory", "Issues", "Media", "Quotes", "Staff"],
  },
  d2d: {
    label: "Door-to-Door Sales",
    description: "Leads, reps, territories, installs, follow-ups, scripts, and sales tracking.",
    modules: ["Leads", "Reps", "Territories", "Installs", "Follow-Ups", "Media", "Reports", "Staff"],
  },
  contractor: {
    label: "Contractor",
    description: "Projects, crews, materials, equipment, tools, change orders, punch lists, and photos.",
    modules: ["Projects", "Crews", "Equipment", "Tools", "Materials", "Issues", "Photos", "Quotes", "Staff"],
  },
  cleaning: {
    label: "Cleaning",
    description: "Properties, recurring visits, crews, checklists, supplies, client notes, and photos.",
    modules: ["Properties", "Crews", "Checklists", "Supplies", "Issues", "Photos", "Clients", "Staff"],
  },
  pest: {
    label: "Pest Control",
    description: "Stops, technicians, treatment notes, chemicals, follow-ups, photos, and routes.",
    modules: ["Stops", "Technicians", "Routes", "Chemicals", "Issues", "Photos", "Customers", "Staff"],
  },
  general: {
    label: "General Field Ops",
    description: "Flexible setup for any crew-based field business.",
    modules: ["Work", "People", "Assets", "Tools", "Inventory", "Issues", "Media", "Reports", "Staff"],
  },
};

export const jobs = [
  {
    id: "job-001",
    name: "Mulch bed cleanup",
    title: "Mulch bed cleanup",
    address: "Oakwood residence",
    status: "Active",
    dept: "Mulch",
    crew: "Chad's Crew",
    eta: "Today 10:30 AM",
    tasks: ["Edge beds", "Install brown mulch", "Clean sidewalk"],
    notes: ["Customer wants photos before leaving."],
  },
  {
    id: "job-002",
    name: "Commercial mowing route",
    title: "Commercial mowing route",
    address: "Wright-Patt contract office",
    status: "Active",
    dept: "Maintenance",
    crew: "Justin's Crew",
    eta: "Today 1:00 PM",
    tasks: ["Mow front zone", "Trim fence line", "Blow walkways"],
    notes: ["Bring trailer 2 and both zero-turns."],
  },
  {
    id: "job-003",
    name: "Drainage walkthrough",
    title: "Drainage walkthrough",
    address: "Downtown office courtyard",
    status: "Scheduled",
    dept: "Landscape / Construction",
    crew: "Joe",
    eta: "Tomorrow 9:00 AM",
    tasks: ["Inspect low spot", "Take photos", "Build quote"],
    notes: ["Needs Joe's eyes before quote."],
  },
  {
    id: "job-004",
    name: "Paver repair and grading",
    title: "Paver repair and grading",
    address: "Centerville patio",
    status: "Scheduled",
    dept: "Landscape / Construction",
    crew: "Jose's Crew",
    eta: "Friday 8:00 AM",
    tasks: ["Pull lifted pavers", "Re-level base", "Compact edge"],
    notes: ["Customer asked for clean before and after photos."],
  },
];

export const crews = [
  {
    id: "crew-chad",
    name: "Chad's Crew",
    status: "Active",
    lead: "Chad",
    people: ["Marcus", "Tyler"],
    available: "After 3 PM",
    dept: "Mulch",
    notes: ["Running mulch and cleanup jobs today."],
  },
  {
    id: "crew-justin",
    name: "Justin's Crew",
    status: "Active",
    lead: "Justin",
    people: ["Evan", "Noah"],
    available: "Tomorrow",
    dept: "Maintenance",
    notes: ["Commercial route and equipment checks."],
  },
  {
    id: "crew-jose",
    name: "Jose's Crew",
    status: "Available",
    lead: "Jose",
    people: ["Miguel", "Luis"],
    available: "Now",
    dept: "Landscape / Construction",
    notes: ["Construction, grading, hardscape, and excavation support."],
  },
  {
    id: "crew-office",
    name: "Office",
    status: "Available",
    lead: "Joe",
    people: ["Amanda", "Riley"],
    available: "Now",
    dept: "Office",
    notes: ["Scheduling, quotes, billing, and customer calls."],
  },
];

export const staffLogins = [
  { id: "joe", name: "Joe", role: "Owner", crew: "Office", pin: "1000", password: "joe" },
  { id: "amanda", name: "Amanda", role: "Manager", crew: "Office", pin: "1001", password: "amanda" },
  { id: "chad", name: "Chad", role: "Crew Lead", crew: "Chad's Crew", pin: "2001", password: "chad" },
  { id: "justin", name: "Justin", role: "Crew Lead", crew: "Justin's Crew", pin: "2002", password: "justin" },
  { id: "jose", name: "Jose", role: "Crew Lead", crew: "Jose's Crew", pin: "2003", password: "jose" },
  { id: "marcus", name: "Marcus", role: "Crew Member", crew: "Chad's Crew", pin: "3001", password: "marcus" },
  { id: "tyler", name: "Tyler", role: "Crew Member", crew: "Chad's Crew", pin: "3002", password: "tyler" },
  { id: "evan", name: "Evan", role: "Crew Member", crew: "Justin's Crew", pin: "3003", password: "evan" },
  { id: "noah", name: "Noah", role: "Crew Member", crew: "Justin's Crew", pin: "3004", password: "noah" },
  { id: "miguel", name: "Miguel", role: "Crew Member", crew: "Jose's Crew", pin: "3005", password: "miguel" },
  { id: "luis", name: "Luis", role: "Crew Member", crew: "Jose's Crew", pin: "3006", password: "luis" },
];

export const equipment = [
  {
    id: "eq-001",
    name: "Truck 1",
    category: "Trucks",
    status: "In Use",
    assigned: "Chad's Crew",
    location: "Oakwood route",
    available: "After 4 PM",
    dept: "Mulch",
    notes: ["Loaded with mulch tools."],
  },
  {
    id: "eq-002",
    name: "Truck 2",
    category: "Trucks",
    status: "Available",
    assigned: "None",
    location: "Yard",
    available: "Now",
    dept: "Maintenance",
    notes: ["Clean and fueled."],
  },
  {
    id: "eq-003",
    name: "Trailer 2",
    category: "Trailers",
    status: "Available",
    assigned: "None",
    location: "Yard",
    available: "Now",
    dept: "Maintenance",
    notes: ["Ready for commercial crew."],
  },
  {
    id: "eq-004",
    name: "Skid Steer 1",
    category: "Skid Steers",
    status: "Needs Service",
    assigned: "None",
    location: "Shop",
    available: "After repair",
    dept: "Landscape / Construction",
    notes: ["Hydraulic leak. Do not dispatch."],
  },
  {
    id: "eq-005",
    name: "Mini Excavator",
    category: "Excavators",
    status: "Available",
    assigned: "None",
    location: "Back lot",
    available: "Now",
    dept: "Landscape / Construction",
    notes: ["Use for drainage and paver base jobs."],
  },
  {
    id: "eq-006",
    name: "Vermeer Trencher",
    category: "Vermeers",
    status: "Available",
    assigned: "None",
    location: "Equipment bay",
    available: "Now",
    dept: "Landscape / Construction",
    notes: ["Check chain tension before use."],
  },
  {
    id: "eq-007",
    name: "Scag Mower",
    category: "Mowers",
    status: "In Use",
    assigned: "Justin's Crew",
    location: "Commercial route",
    available: "After 2 PM",
    dept: "Maintenance",
    notes: ["Fuel before next route."],
  },
  {
    id: "eq-008",
    name: "Walk-behind Mower",
    category: "Mowers",
    status: "Available",
    assigned: "None",
    location: "Mower bay",
    available: "Now",
    dept: "Maintenance",
    notes: ["Good for tight gates."],
  },
];

export const tools = [
  {
    id: "tool-001",
    name: "Stihl BR 800 Blower",
    category: "Blowers",
    status: "Available",
    assigned: "None",
    location: "Tool rack A",
    available: "Now",
    dept: "Maintenance",
    notes: ["Backpack blower. Keep mixed fuel nearby."],
  },
  {
    id: "tool-002",
    name: "Stihl Trimmer 1",
    category: "Trimmers",
    status: "In Use",
    assigned: "Justin's Crew",
    location: "Truck 1",
    available: "After route",
    dept: "Maintenance",
    notes: ["Fresh line installed."],
  },
  {
    id: "tool-003",
    name: "Plate Compactor",
    category: "Hardscape",
    status: "Available",
    assigned: "None",
    location: "Shop floor",
    available: "Now",
    dept: "Landscape / Construction",
    notes: ["Needed for paver and base jobs."],
  },
  {
    id: "tool-004",
    name: "Laser Level Kit",
    category: "Layout",
    status: "Available",
    assigned: "Joe",
    location: "Office shelf",
    available: "Now",
    dept: "Landscape / Construction",
    notes: ["Return to office after drainage jobs."],
  },
  {
    id: "tool-005",
    name: "Wheelbarrow Set",
    category: "Hand Tools",
    status: "Available",
    assigned: "None",
    location: "Yard gate",
    available: "Now",
    dept: "Mulch",
    notes: ["Four wheelbarrows total."],
  },
  {
    id: "tool-006",
    name: "Shovel / Rake Kit",
    category: "Hand Tools",
    status: "Available",
    assigned: "None",
    location: "Tool rack B",
    available: "Now",
    dept: "Mulch",
    notes: ["Keep one kit per crew truck."],
  },
];

export const inventory = [
  {
    id: "inv-001",
    name: "Brown mulch",
    category: "Materials",
    qty: 42,
    unit: "yards",
    status: "Good",
    dept: "Mulch",
    notes: ["Main yard pile."],
  },
  {
    id: "inv-002",
    name: "Black mulch",
    category: "Materials",
    qty: 8,
    unit: "yards",
    status: "Low",
    dept: "Mulch",
    notes: ["Order more before weekend."],
  },
  {
    id: "inv-003",
    name: "River rock",
    category: "Materials",
    qty: 14,
    unit: "tons",
    status: "Good",
    dept: "Landscape / Construction",
    notes: ["Back left bin."],
  },
  {
    id: "inv-004",
    name: "Topsoil",
    category: "Materials",
    qty: 22,
    unit: "yards",
    status: "Good",
    dept: "Landscape / Construction",
    notes: ["Covered pile."],
  },
  {
    id: "inv-005",
    name: "Trimmer line",
    category: "Small Tools",
    qty: 18,
    unit: "spools",
    status: "Good",
    dept: "Maintenance",
    notes: ["Shelf B."],
  },
  {
    id: "inv-006",
    name: "Fuel mix",
    category: "Fuel / Fluids",
    qty: 6,
    unit: "cans",
    status: "Low",
    dept: "Maintenance",
    notes: ["Justin's Crew needs refill."],
  },
  {
    id: "inv-007",
    name: "Safety cones",
    category: "Safety",
    qty: 20,
    unit: "cones",
    status: "Good",
    dept: "Maintenance",
    notes: ["Stacked by loading door."],
  },
];

export const issues = [
  {
    id: "issue-001",
    name: "Skid Steer hydraulic leak",
    title: "Skid Steer hydraulic leak",
    severity: "High",
    status: "Open",
    owner: "Joe",
    dept: "Landscape / Construction",
    notes: ["Parked in shop. Needs service before dispatch."],
  },
  {
    id: "issue-002",
    name: "Black mulch running low",
    title: "Black mulch running low",
    severity: "Medium",
    status: "Open",
    owner: "Amanda",
    dept: "Mulch",
    notes: ["Only 8 yards left."],
  },
  {
    id: "issue-003",
    name: "Trailer lights fixed",
    title: "Trailer lights fixed",
    severity: "Low",
    status: "Resolved",
    owner: "Chad",
    dept: "Maintenance",
    notes: ["Resolved yesterday."],
  },
  {
    id: "issue-004",
    name: "Mini excavator thumb pin check",
    title: "Mini excavator thumb pin check",
    severity: "Medium",
    status: "Open",
    owner: "Jose",
    dept: "Landscape / Construction",
    notes: ["Jose noticed looseness during last dig."],
  },
];
