"use client";

/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import { useCompanies } from "@/lib/fieldflow/useCompanies";
import { Bell, CheckCircle2, ChevronRight, ClipboardList, Gauge, LogOut, Package, Plus, Save, ShieldCheck, Trash2, Truck, UserCog, Wrench, Users, X } from "lucide-react";
import { fetchDeviceSession, logoutDeviceSession } from "@/lib/fieldflow/deviceAuth";
import { loadLiveBoard, saveLiveBoard, subscribeLiveBoard, NexusBoardData } from "@/lib/fieldflow/liveStore";
import { inventoryCategories } from "@/lib/v2Additions";
import { seedBoardForCompany } from "@/lib/fieldflow/seedBoards";

type View = "dashboard" | "work" | "equipment" | "tools" | "inventory" | "issues" | "staff";
type DrawerType = "job" | "equipment" | "tool" | "inventory" | "issue" | "staff" | "request" | "checkout" | "message";
type Drawer = { type: DrawerType; title: string; payload: any; mode?: "edit" | "add" } | null;
type RequestStatus = "Pending" | "Approved" | "Denied" | "Completed";
type RequestItem = { id: string; kind: string; item: string; assetIds?: string[]; requestedBy: string; crew: string; status: RequestStatus; note: string; startDate?: string; endDate?: string; createdAt: string };

type BoardState = Required<NexusBoardData>;

const permissions = [["manage_company_admins", "Ordain company admins"], ["manage_managers", "Ordain managers"], ["manage_staff", "Manage staff"], ["approve_requests", "Approve requests"], ["edit_jobs", "Edit jobs"], ["edit_inventory", "Edit inventory"], ["edit_equipment", "Edit equipment/tools"], ["edit_issues", "Edit issues"], ["post_messages", "Post messages"], ["upload_media", "Upload media"], ["request_assets", "Request assets"]] as const;
const nav = [["Command", [["/dashboard", "Dashboard", Gauge], ["/work", "Jobs", ClipboardList], ["/staff", "Staff + Crews", UserCog], ["/crew", "Crew Portal", Users]]], ["Assets", [["/equipment", "Equipment", Truck], ["/tools", "Tools", Wrench], ["/inventory", "Inventory", Package], ["/issues", "Issues", Bell]]]] as const;
const FALLBACK_DEPTS = ["Landscape / Construction", "Mulch", "Maintenance", "Office", "Operations", "Greenhouse", "Sales"];
const EQUIPMENT_CATS = ["All", "Trucks", "Trailers", "Excavators", "Skid Steers", "Vermeers", "Mowers", "Sales Kit", "Connectivity", "Vehicle", "Small Tools"];
const TOOL_CATS = ["All", "Hand Tools", "Power Tools", "Hardscape", "Layout", "Safety", "Sales Materials", "Power"];

function tone(v = "") { if (["Available", "Good", "Resolved", "Approved", "Completed", "Checked In"].includes(v)) return "green"; if (["Needs Service", "Low", "Open", "High", "Denied", "Out"].includes(v)) return "red"; if (["Active", "In Use", "Pending", "Checked Out"].includes(v)) return "blue"; if (["Medium", "Scheduled"].includes(v)) return "gold"; return ""; }
function Pill({ children, t = "" }: { children: React.ReactNode; t?: string }) { return <span className={`ff-pill ${t}`}>{children}</span>; }
function Button({ children, onClick, variant = "primary", type = "button" }: { children: React.ReactNode; onClick?: () => void; variant?: "primary" | "secondary" | "danger"; type?: "button" | "submit" }) { return <button type={type} onClick={onClick} className={`ff-btn ${variant}`}>{children}</button>; }
function Panel({ title, note, action, children }: { title: string; note?: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="ff-panel"><div className="ff-panel-head"><div><h3>{title}</h3>{note ? <p>{note}</p> : null}</div>{action}</div><div className="ff-panel-body">{children}</div></section>; }
function Kpi({ label, value }: { label: string; value: string | number }) { return <div className="ff-kpi"><div className="label">{label}</div><div className="num">{value}</div></div>; }
function Field({ label, value, onChange, textarea = false, type = "text" }: { label: string; value: any; onChange: (v: string) => void; textarea?: boolean; type?: string }) { return <label className="ff-edit-field"><span>{label}</span>{textarea ? <textarea value={value ?? ""} onChange={(e) => onChange(e.target.value)} /> : <input type={type} value={value ?? ""} onChange={(e) => onChange(e.target.value)} />}</label>; }
function SelectField({ label, value, onChange, options }: { label: string; value: any; onChange: (v: string) => void; options: string[] }) { const opts = Array.from(new Set([value, ...options].filter(Boolean))); return <label className="ff-edit-field"><span>{label}</span><select value={value ?? ""} onChange={(e) => onChange(e.target.value)}>{opts.map((o) => <option key={o} value={o}>{o}</option>)}</select></label>; }
function noteText(item: any) { return Array.isArray(item.notes) ? item.notes.join("\n") : item.notes ?? ""; }
function lines(value: string) { return value.split("\n").map((x) => x.trim()).filter(Boolean); }
function uid(prefix: string) { return `${prefix}-${Date.now()}`; }
function today() { return new Date().toISOString().slice(0, 10); }
function plusDays(days: number) { const d = new Date(); d.setDate(d.getDate() + days); return d.toISOString().slice(0, 10); }
function phoneLastFour(value = "") { return value.replace(/\D/g, "").slice(-4); }
function normalizeBoard(data: NexusBoardData, slug: string): BoardState { return { jobs: data.jobs || [], equipment: data.equipment || [], tools: data.tools || [], inventory: data.inventory || [], issues: data.issues || [], staff: data.staff || [], crews: data.crews || [], messages: data.messages || [], requests: data.requests || [], checkouts: data.checkouts || [], updatedAt: data.updatedAt || "", companySlug: slug }; }
function emptyBoard(slug: string): BoardState { return normalizeBoard({ jobs: [], equipment: [], tools: [], inventory: [], issues: [], staff: [], crews: [], messages: [], requests: [], checkouts: [] }, slug); }
function assetLabel(a: any) { return `${a.name}${a.assigned && a.assigned !== "None" ? ` · ${a.assigned}` : ""}`; }

function Card({ item, type, setDrawer }: { item: any; type: DrawerType; setDrawer: (d: Drawer) => void }) {
  const title = item.name || item.title || item.item;
  return <article className="ff-card" onClick={() => setDrawer({ type, title, payload: item, mode: "edit" })}>
    <div className="ff-card-top"><div><h4>{title}</h4><p>{item.address || item.location || item.owner || item.crew || `${item.qty ?? ""} ${item.unit ?? ""}`}</p></div><Pill t={tone(item.status || item.severity)}>{item.status || item.severity}</Pill></div>
    {item.notes?.[0] || item.note ? <div className="ff-note">{item.notes?.[0] || item.note}</div> : null}
    <div className="ff-meta">
      {type === "job" && <><div><span>Crew</span><strong>{item.crew}</strong></div><div><span>Finish</span><strong>{item.estimatedFinish || item.eta}</strong></div><div><span>Tasks</span><strong>{item.tasks?.length ?? 0}</strong></div></>}
      {(type === "equipment" || type === "tool") && <><div><span>Category</span><strong>{item.category}</strong></div><div><span>Assigned</span><strong>{item.assigned}</strong></div><div><span>Available</span><strong>{item.available}</strong></div></>}
      {type === "inventory" && <><div><span>Qty</span><strong>{item.qty}</strong></div><div><span>Unit</span><strong>{item.unit}</strong></div><div><span>Status</span><strong>{item.status}</strong></div></>}
      {type === "issue" && <><div><span>Severity</span><strong>{item.severity}</strong></div><div><span>Owner</span><strong>{item.owner}</strong></div><div><span>Status</span><strong>{item.status}</strong></div></>}
      {type === "staff" && <><div><span>Role</span><strong>{item.role}</strong></div><div><span>Crew</span><strong>{item.crew}</strong></div><div><span>Available</span><strong>{item.available}</strong></div></>}
      {(type === "request" || type === "checkout") && <><div><span>By</span><strong>{item.requestedBy || item.person}</strong></div><div><span>Crew</span><strong>{item.crew}</strong></div><div><span>Dates</span><strong>{item.startDate || "Today"} → {item.endDate || "Today"}</strong></div></>}
      {type === "message" && <><div><span>Author</span><strong>{item.author}</strong></div><div><span>Audience</span><strong>{item.audience}</strong></div><div><span>Date</span><strong>{String(item.createdAt || "").slice(0,10)}</strong></div></>}
    </div>
  </article>;
}

export function ManagerApp({ view, companySlug }: { view: View; companySlug?: string }) {
  const pathname = usePathname();
  const router = useRouter();
  const { activeCompany, loading, selectCompany } = useCompanies();
  const [open, setOpen] = useState(false);
  const [drawer, setDrawer] = useState<Drawer>(null);
  const [edit, setEdit] = useState<any>(null);
  const [search, setSearch] = useState("");
  const [dept, setDept] = useState("all");
  const [status, setStatus] = useState("all");
  const [cat, setCat] = useState("All");
  const [inventoryCategory, setInventoryCategory] = useState("All");
  const [board, setBoard] = useState<BoardState>(() => emptyBoard(activeCompany.slug));
  const [syncStatus, setSyncStatus] = useState("Loading company board...");
  const [boardSlug, setBoardSlug] = useState("");
  const loadedSlug = useRef("");
  const hydrated = useRef(false);
  const dirty = useRef(false);

  const fallbackBoard = useMemo<NexusBoardData>(() => seedBoardForCompany(activeCompany.slug), [activeCompany.slug]);
  const crewOptions = useMemo(() => Array.from(new Set([...(board.crews || []).map((c:any)=>c.name), ...board.staff.map((p: any) => p.crew)].filter(Boolean))).sort(), [board.crews, board.staff]);
  const personOptions = useMemo(() => Array.from(new Set(board.staff.map((p: any) => p.name).filter(Boolean))).sort(), [board.staff]);
  const deptOptions = useMemo(() => Array.from(new Set([...FALLBACK_DEPTS, ...(board.crews || []).map((x:any)=>x.dept), ...board.jobs.map((x:any)=>x.dept), ...board.equipment.map((x:any)=>x.dept), ...board.tools.map((x:any)=>x.dept), ...board.staff.map((x:any)=>x.dept)].filter(Boolean))).sort(), [board]);
  const assets = useMemo(() => [...board.equipment.map((x:any)=>({...x, assetType:"equipment"})), ...board.tools.map((x:any)=>({...x, assetType:"tool"}))], [board.equipment, board.tools]);
  const availableAssets = assets.filter((a:any) => a.status !== "Needs Service" && a.status !== "In Use");

  useEffect(() => { fetchDeviceSession().then((session) => { if (!session) router.replace("/"); if (companySlug && session && session.role !== "owner" && session.slug !== companySlug) router.replace("/"); if (session && !["owner", "admin", "manager"].includes(session.role)) router.replace(`/${session.slug}/crew`); }).catch(() => router.replace("/")); }, [router, companySlug]);
  useEffect(() => { if (!loading && companySlug && activeCompany.slug !== companySlug) selectCompany(companySlug); }, [loading, companySlug, activeCompany.slug, selectCompany]);
  useEffect(() => { let live = true; hydrated.current = false; dirty.current = false; loadedSlug.current = ""; setBoardSlug(""); setDrawer(null); setEdit(null); setBoard(emptyBoard(activeCompany.slug)); setSyncStatus(`Loading ${activeCompany.companyName}...`); loadLiveBoard(activeCompany.slug, fallbackBoard).then((data) => { if (!live) return; dirty.current = false; setBoard(normalizeBoard(data, activeCompany.slug)); loadedSlug.current = activeCompany.slug; hydrated.current = true; setBoardSlug(activeCompany.slug); setSyncStatus("Company board loaded."); }); return () => { live = false; }; }, [activeCompany.slug, activeCompany.companyName, fallbackBoard]);
  useEffect(() => subscribeLiveBoard(activeCompany.slug, (data) => { if (loadedSlug.current !== activeCompany.slug || dirty.current) return; setBoard(normalizeBoard(data, activeCompany.slug)); }, setSyncStatus), [activeCompany.slug]);
  useEffect(() => { if (!dirty.current || !hydrated.current || loadedSlug.current !== activeCompany.slug) return; const timer = window.setTimeout(async () => { const result = await saveLiveBoard(activeCompany.slug, board); if (result.ok) dirty.current = false; setSyncStatus(result.ok ? "Saved live. Realtime ready." : `Local save OK. Live sync needs setup: ${result.message}`); }, 450); return () => window.clearTimeout(timer); }, [activeCompany.slug, board]);
  useEffect(() => { if (drawer) setEdit({ ...drawer.payload, notesText: noteText(drawer.payload), tasksText: Array.isArray(drawer.payload.tasks) ? drawer.payload.tasks.join("\n") : "" }); }, [drawer?.payload?.id, drawer?.mode]);

  const q = search.toLowerCase();
  function pass(x: any) { const txt = JSON.stringify(x).toLowerCase(); if (q && !txt.includes(q)) return false; if (dept !== "all" && x.dept && x.dept !== dept) return false; if (status !== "all" && x.status && x.status !== status) return false; return true; }
  const fe = board.equipment.filter((e:any) => (cat === "All" || e.category === cat)).filter(pass);
  const ft = board.tools.filter((t:any) => (cat === "All" || t.category === cat)).filter(pass);
  const filteredInventory = board.inventory.filter((i: any) => inventoryCategory === "All" || i.category === inventoryCategory).filter(pass);
  const filteredStaff = board.staff.filter(pass);
  const roles = ["Company Admin", "Office Manager", "Manager", "Crew Lead", "Greenhouse Lead", "Maintenance", "Crew Member"];

  function setList(key: keyof BoardState, updater: (list: any[]) => any[]) { dirty.current = true; setBoard((b) => ({ ...b, [key]: updater((b[key] as any[]) || []) })); }
  function openAdd(type: DrawerType) {
    const blank: Record<DrawerType, any> = {
      job: { id: uid("job"), name: "New Job", title: "New Job", address: "", status: "Scheduled", dept: deptOptions[0] || "Maintenance", crew: crewOptions[0] || "Crew A", scheduledStart: today(), estimatedFinish: "", dueDate: "", tasks: [], notes: [] },
      equipment: { id: uid("eq"), name: "New Equipment", category: "Trucks", status: "Available", assigned: "None", location: "Yard", available: "Now", dept: deptOptions[0] || "Maintenance", notes: [] },
      tool: { id: uid("tool"), name: "New Tool", category: "Hand Tools", status: "Available", assigned: "None", location: "Tool rack", available: "Now", dept: deptOptions[0] || "Maintenance", notes: [] },
      inventory: { id: uid("inv"), name: "New Inventory Item", category: "Other", qty: 0, unit: "each", status: "Good", dept: deptOptions[0] || "Maintenance", notes: [] },
      issue: { id: uid("issue"), name: "New Issue", title: "New Issue", severity: "Medium", status: "Open", owner: personOptions[0] || "Manager", dept: deptOptions[0] || "Maintenance", notes: [] },
      staff: { id: uid("staff"), name: "New Person", role: "Crew Member", crew: crewOptions[0] || "Crew A", dept: deptOptions[0] || "Maintenance", status: "Active", available: "Now", phone: "", pin: "", tempPin: "", password: "", mustChangePassword: true, accessLevel: "crew", permissions: ["request_assets", "upload_media"] },
      request: { id: uid("req"), kind: "Checkout", item: "", assetIds: [], requestedBy: personOptions[0] || "Manager", crew: crewOptions[0] || "Crew A", status: "Pending", note: "", startDate: today(), endDate: today(), createdAt: new Date().toISOString() },
      checkout: { id: uid("out"), item: "", assetIds: [], person: personOptions[0] || "Manager", requestedBy: personOptions[0] || "Manager", crew: crewOptions[0] || "Crew A", status: "Checked Out", note: "", startDate: today(), endDate: today(), createdAt: new Date().toISOString() },
      message: { id: uid("msg"), title: "New message", body: "", audience: "All", author: personOptions[0] || "Manager", pinned: false, createdAt: new Date().toISOString() },
    };
    setDrawer({ type, title: `Add ${type}`, payload: blank[type], mode: "add" });
  }
  function cleanEdit() { const clean = { ...edit }; if ("notesText" in clean) { clean.notes = lines(clean.notesText); delete clean.notesText; } if ("tasksText" in clean) { clean.tasks = lines(clean.tasksText); delete clean.tasksText; } return clean; }
  function applyAssetCheckout(item: any, status: "In Use" | "Available") { const ids = item.assetIds || []; dirty.current = true; setBoard((b) => ({ ...b, equipment: b.equipment.map((a:any) => ids.includes(a.id) ? { ...a, status, assigned: status === "In Use" ? item.crew : "None", available: status === "In Use" ? `Until ${item.endDate || "return"}` : "Now" } : a), tools: b.tools.map((a:any) => ids.includes(a.id) ? { ...a, status, assigned: status === "In Use" ? item.crew : "None", available: status === "In Use" ? `Until ${item.endDate || "return"}` : "Now" } : a) })); }
  function saveEdit() { if (!drawer || !edit) return; const clean = cleanEdit(); if (drawer.type === "job") setList("jobs", (l) => drawer.mode === "add" ? [clean, ...l] : l.map((x) => x.id === clean.id ? clean : x)); if (drawer.type === "equipment") setList("equipment", (l) => drawer.mode === "add" ? [clean, ...l] : l.map((x) => x.id === clean.id ? clean : x)); if (drawer.type === "tool") setList("tools", (l) => drawer.mode === "add" ? [clean, ...l] : l.map((x) => x.id === clean.id ? clean : x)); if (drawer.type === "inventory") setList("inventory", (l) => drawer.mode === "add" ? [clean, ...l] : l.map((x) => x.id === clean.id ? clean : x)); if (drawer.type === "issue") setList("issues", (l) => drawer.mode === "add" ? [clean, ...l] : l.map((x) => x.id === clean.id ? clean : x)); if (drawer.type === "staff") setList("staff", (l) => drawer.mode === "add" ? [clean, ...l] : l.map((x) => x.id === clean.id ? clean : x)); if (drawer.type === "request") setList("requests", (l) => drawer.mode === "add" ? [clean, ...l] : l.map((x) => x.id === clean.id ? clean : x)); if (drawer.type === "checkout") { setList("checkouts", (l) => drawer.mode === "add" ? [clean, ...l] : l.map((x) => x.id === clean.id ? clean : x)); applyAssetCheckout(clean, clean.status === "Checked In" ? "Available" : "In Use"); } if (drawer.type === "message") setList("messages", (l) => drawer.mode === "add" ? [{ ...clean, createdAt: clean.createdAt || new Date().toISOString() }, ...l] : l.map((x) => x.id === clean.id ? clean : x)); setDrawer(null); }
  function deleteItem() { if (!drawer || !edit) return; const key = drawer.type === "job" ? "jobs" : drawer.type === "equipment" ? "equipment" : drawer.type === "tool" ? "tools" : drawer.type === "inventory" ? "inventory" : drawer.type === "issue" ? "issues" : drawer.type === "staff" ? "staff" : drawer.type === "checkout" ? "checkouts" : drawer.type === "message" ? "messages" : "requests"; setList(key as keyof BoardState, (l) => l.filter((x) => x.id !== edit.id)); setDrawer(null); }
  function clearList(key: keyof BoardState, label: string) { if (!window.confirm(`Delete all ${label} for ${activeCompany.companyName}?`)) return; setList(key, () => []); }
  function clearPeople() { if (!window.confirm(`Delete all people and crews for ${activeCompany.companyName}?`)) return; dirty.current = true; setBoard((b) => ({ ...b, staff: [], crews: [] })); }
  function updateRequest(id: string, nextStatus: RequestStatus) { const req = board.requests.find((r:any) => r.id === id); setList("requests", (l) => l.map((r) => r.id === id ? { ...r, status: nextStatus } : r)); if (req && nextStatus === "Approved") { const checkout = { ...req, id: uid("out"), person: req.requestedBy, status: "Checked Out", createdAt: new Date().toISOString() }; setList("checkouts", (l) => [checkout, ...l]); applyAssetCheckout(checkout, "In Use"); } }
  function patch(k: string, v: any) { setEdit((current: any) => ({ ...current, [k]: v })); }
  function patchStaffPhone(value: string) {
    setEdit((current: any) => {
      const lastFour = phoneLastFour(value);
      const shouldSuggestPin = lastFour.length === 4 && !current.pin && !current.tempPin;
      return {
        ...current,
        phone: value,
        ...(shouldSuggestPin ? { pin: lastFour, tempPin: lastFour } : {}),
      };
    });
  }
  function toggleAsset(id: string) { setEdit((current: any) => { const currentIds = Array.isArray(current.assetIds) ? current.assetIds : []; const asset = assets.find((a:any)=>a.id===id); const nextIds = currentIds.includes(id) ? currentIds.filter((x:string)=>x!==id) : [...currentIds, id]; const names = assets.filter((a:any)=>nextIds.includes(a.id)).map((a:any)=>a.name).join(", "); return { ...current, assetIds: nextIds, item: names || current.item }; }); }
  function togglePerm(key: string) { setEdit((current: any) => { const ps = Array.isArray(current.permissions) ? current.permissions : []; return { ...current, permissions: ps.includes(key) ? ps.filter((x: string) => x !== key) : [...ps, key] }; }); }
  async function logout() { await logoutDeviceSession(); router.push("/"); }
  const waitingForCompany = loading || (companySlug ? activeCompany.slug !== companySlug : false);
  const boardReady = boardSlug === activeCompany.slug;

  if (waitingForCompany || !boardReady) {
    return <main className="ff-light-page"><div className="ff-loading-shell"><div className="nexus-sync-pill">{waitingForCompany ? "Loading company..." : syncStatus}</div></div></main>;
  }

  return <main className="ff-light-page"><div className="ff-shell">
    <aside className={`ff-sidebar ${open ? "open" : ""}`}><div className="ff-brand"><div className="ff-brand-row"><div className="ff-logo ff-nexus-logo"><img src="/brand/nexus-app-icon.png" alt="Nexus" /></div><div><h1>Nexus</h1><p>Manager board</p></div></div><div className="ff-company-box"><div className="micro">Signed into</div><strong>{activeCompany.companyName}</strong><div style={{ marginTop: 8, display: "flex", gap: 6, flexWrap: "wrap" }}><Pill t="green">{activeCompany.template}</Pill><Pill>{activeCompany.modules.length} modules</Pill></div><button className="ff-logout-mini" onClick={logout}><LogOut size={14}/> Logout</button></div></div><nav className="ff-nav">{nav.map(([g, links]) => <div key={g}><div className="ff-nav-label">{g}</div>{links.map(([href, label, Icon]) => <Link key={label} href={`/${activeCompany.slug}${href}`} className={`ff-nav-link ${pathname === `/${activeCompany.slug}${href}` ? "active" : ""}`}><span style={{ display: "flex", gap: 10, alignItems: "center" }}><Icon size={18} />{label}</span><ChevronRight size={14} /></Link>)}</div>)}</nav></aside>
    <section className="ff-main"><header className="ff-top"><div className="ff-top-inner"><div className="ff-top-row"><div className="ff-title"><div className="micro">{activeCompany.companyName} Manager</div><h2>{view === "dashboard" ? "Office board" : view[0].toUpperCase() + view.slice(1)}</h2><p>Synced jobs, crews, tools, equipment, checkout requests, and manager approvals.</p></div><div className="ff-actions"><button className="ff-mobile-menu" onClick={() => setOpen(!open)}>☰</button><span className="nexus-sync-pill">{syncStatus}</span><Button variant="secondary" onClick={logout}><LogOut size={17}/> Logout</Button>{view === "dashboard" ? <Button onClick={() => openAdd("checkout")}><Plus /> Checkout</Button> : null}</div></div></div></header>
    <div className="ff-content"><div className="ff-controls"><input className="ff-input" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search truck, crew, job, material, person, location..." /><select className="ff-input" value={dept} onChange={(e) => setDept(e.target.value)}><option value="all">All departments</option>{deptOptions.map((d)=><option key={d}>{d}</option>)}</select><select className="ff-input" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option><option>Available</option><option>In Use</option><option>Active</option><option>Scheduled</option><option>Pending</option><option>Open</option><option>Low</option><option>Needs Service</option></select></div>
    {view === "dashboard" && <><div className="ff-kpis"><Kpi label="Jobs" value={board.jobs.length} /><Kpi label="Pending Requests" value={board.requests.filter((r:any)=>r.status==="Pending").length} /><Kpi label="Checked Out" value={board.checkouts.filter((c:any)=>c.status!=="Checked In").length} /><Kpi label="Available Assets" value={availableAssets.length} /></div><Panel title="Message Board" note="Company-wide notes without turning this into bloated DMs yet." action={<Button onClick={() => openAdd("message")}><Plus /> Post</Button>}><div className="ff-grid">{board.messages.length ? board.messages.filter(pass).map((m:any) => <Card key={m.id} item={{...m, name:m.title, note:m.body, status:m.pinned ? "Pinned" : "Active"}} type="message" setDrawer={setDrawer} />) : <div className="ff-empty-box">No messages yet.</div>}</div></Panel><Panel title="Crew Checkout Requests" note="Approve requests and the exact tools/equipment move to checked out automatically." action={<Button onClick={() => openAdd("request")}><Plus /> Add Request</Button>}><div className="ff-grid">{board.requests.length ? board.requests.filter(pass).map((r:any) => <Card key={r.id} item={r} type="request" setDrawer={setDrawer} />) : <div className="ff-empty-box">No crew requests yet.</div>}</div></Panel><Panel title="Currently Checked Out"><div className="ff-grid">{board.checkouts.length ? board.checkouts.filter(pass).map((c:any) => <Card key={c.id} item={c} type="checkout" setDrawer={setDrawer} />) : <div className="ff-empty-box">Nothing is checked out.</div>}</div></Panel><Panel title="Today’s Jobs"><div className="ff-grid">{board.jobs.filter(pass).map((j:any) => <Card key={j.id} item={j} type="job" setDrawer={setDrawer} />)}</div></Panel></>}
    {view === "work" && <Panel title="Jobs" action={<div className="ff-panel-actions"><Button variant="secondary" onClick={() => clearList("jobs", "jobs")}><Trash2 /> Clear Jobs</Button><Button onClick={() => openAdd("job")}><Plus /> Add Job</Button></div>}><div className="ff-grid">{board.jobs.filter(pass).map((j:any) => <Card key={j.id} item={j} type="job" setDrawer={setDrawer} />)}</div></Panel>}
    {view === "equipment" && <Panel title="Equipment" action={<div className="ff-panel-actions"><Button variant="secondary" onClick={() => clearList("equipment", "equipment")}><Trash2 /> Clear Equipment</Button><Button onClick={() => openAdd("equipment")}><Plus /> Add Equipment</Button></div>}><div className="ff-cats">{EQUIPMENT_CATS.map((c) => <button key={c} onClick={() => setCat(c)} className={`ff-cat ${cat === c ? "active" : ""}`}>{c}</button>)}</div><div className="ff-grid">{fe.map((e:any) => <Card key={e.id} item={e} type="equipment" setDrawer={setDrawer} />)}</div></Panel>}
    {view === "tools" && <Panel title="Tools" note="Reusable hand tools, power tools, sales materials, and crew kits." action={<div className="ff-panel-actions"><Button variant="secondary" onClick={() => clearList("tools", "tools")}><Trash2 /> Clear Tools</Button><Button onClick={() => openAdd("tool")}><Plus /> Add Tool</Button></div>}><div className="ff-cats">{TOOL_CATS.map((c) => <button key={c} onClick={() => setCat(c)} className={`ff-cat ${cat === c ? "active" : ""}`}>{c}</button>)}</div><div className="ff-grid">{ft.map((t:any) => <Card key={t.id} item={t} type="tool" setDrawer={setDrawer} />)}</div></Panel>}
    {view === "inventory" && <Panel title="Inventory" note="Consumables live here. Reusable assets live in tools/equipment and can be checked out." action={<div className="ff-panel-actions"><Button variant="secondary" onClick={() => clearList("inventory", "inventory")}><Trash2 /> Clear Inventory</Button><Button onClick={() => openAdd("inventory")}><Plus /> Add Item</Button></div>}><div className="ff-inventory-tabs">{inventoryCategories.map((c) => <button key={c} className={`ff-inventory-tab ${inventoryCategory === c ? "active" : ""}`} onClick={() => setInventoryCategory(c)}>{c}</button>)}</div><div className="ff-grid">{filteredInventory.map((i:any) => <Card key={i.id} item={i} type="inventory" setDrawer={setDrawer} />)}</div></Panel>}
    {view === "staff" && <Panel title="Staff + Crews" note="The job editor and request forms now pull crew/person options from this staff list." action={<div className="ff-panel-actions"><Button variant="secondary" onClick={clearPeople}><Trash2 /> Clear People</Button><Button onClick={() => openAdd("staff")}><Plus /> Add Person</Button></div>}><div className="ff-staff-groups">{roles.map((role) => { const group = filteredStaff.filter((p: any) => p.role === role); if (!group.length) return null; return <section className="ff-staff-group" key={role}><div className="ff-staff-group-head"><h4>{role}</h4><Pill>{group.length}</Pill></div><div className="ff-grid">{group.map((person: any) => <Card key={person.id} item={person} type="staff" setDrawer={setDrawer} />)}</div></section>; })}</div></Panel>}
    {view === "issues" && <Panel title="Issues" action={<div className="ff-panel-actions"><Button variant="secondary" onClick={() => clearList("issues", "issues")}><Trash2 /> Clear Issues</Button><Button onClick={() => openAdd("issue")}><Plus /> Add Issue</Button></div>}><div className="ff-grid">{board.issues.filter(pass).map((i:any) => <Card key={i.id} item={i} type="issue" setDrawer={setDrawer} />)}</div></Panel>}
    </div></section></div>
    <aside className={`ff-drawer ${drawer ? "open" : ""}`}><div className="ff-drawer-head"><div><div className="ff-drawer-title">{drawer?.mode === "add" ? drawer?.title : edit?.name || edit?.title || edit?.item}</div><div className="micro">{drawer?.type} editor</div></div><div className="ff-drawer-tools">{drawer?.mode === "edit" ? <Button variant="danger" onClick={deleteItem}><Trash2 /> Delete</Button> : null}<Button variant="secondary" onClick={() => setDrawer(null)}><X /> Close</Button></div></div><div className="ff-drawer-body">{drawer && edit ? <div className="ff-edit-form">
      {drawer.type === "job" && <><Field label="Job name" value={edit.name} onChange={(v) => { patch("name", v); patch("title", v); }} /><Field label="Address" value={edit.address} onChange={(v) => patch("address", v)} /><SelectField label="Status" value={edit.status} onChange={(v) => patch("status", v)} options={["Scheduled", "Active", "Completed", "Paused"]} /><SelectField label="Department" value={edit.dept} onChange={(v) => patch("dept", v)} options={deptOptions} /><SelectField label="Crew" value={edit.crew} onChange={(v) => patch("crew", v)} options={crewOptions} /><Field label="Scheduled start" type="date" value={edit.scheduledStart || today()} onChange={(v) => patch("scheduledStart", v)} /><Field label="Estimated finish" value={edit.estimatedFinish || edit.eta} onChange={(v) => { patch("estimatedFinish", v); patch("eta", v); }} /><Field label="Due date" type="date" value={edit.dueDate} onChange={(v) => patch("dueDate", v)} /><Field label="Tasks" value={edit.tasksText} textarea onChange={(v) => patch("tasksText", v)} /><Field label="Notes" value={edit.notesText} textarea onChange={(v) => patch("notesText", v)} /></>}
      {(drawer.type === "equipment" || drawer.type === "tool") && <><Field label="Name" value={edit.name} onChange={(v) => patch("name", v)} /><SelectField label="Category" value={edit.category} onChange={(v) => patch("category", v)} options={(drawer.type === "equipment" ? EQUIPMENT_CATS : TOOL_CATS).filter((c) => c !== "All")} /><SelectField label="Status" value={edit.status} onChange={(v) => patch("status", v)} options={["Available", "In Use", "Needs Service"]} /><SelectField label="Assigned" value={edit.assigned} onChange={(v) => patch("assigned", v)} options={["None", ...crewOptions, ...personOptions]} /><Field label="Location" value={edit.location} onChange={(v) => patch("location", v)} /><Field label="Available" value={edit.available} onChange={(v) => patch("available", v)} /><SelectField label="Department" value={edit.dept} onChange={(v) => patch("dept", v)} options={deptOptions} /><Field label="Notes" value={edit.notesText} textarea onChange={(v) => patch("notesText", v)} /></>}
      {drawer.type === "inventory" && <><Field label="Name" value={edit.name} onChange={(v) => patch("name", v)} /><SelectField label="Category" value={edit.category} onChange={(v) => patch("category", v)} options={inventoryCategories.filter((c) => c !== "All")} /><Field label="Qty" value={edit.qty} type="number" onChange={(v) => patch("qty", Number(v))} /><Field label="Unit" value={edit.unit} onChange={(v) => patch("unit", v)} /><SelectField label="Status" value={edit.status} onChange={(v) => patch("status", v)} options={["Good", "Low", "Out"]} /><SelectField label="Department" value={edit.dept} onChange={(v) => patch("dept", v)} options={deptOptions} /><Field label="Notes" value={edit.notesText} textarea onChange={(v) => patch("notesText", v)} /></>}
      {drawer.type === "issue" && <><Field label="Issue" value={edit.name} onChange={(v) => { patch("name", v); patch("title", v); }} /><SelectField label="Severity" value={edit.severity} onChange={(v) => patch("severity", v)} options={["Low", "Medium", "High"]} /><SelectField label="Status" value={edit.status} onChange={(v) => patch("status", v)} options={["Open", "Resolved"]} /><SelectField label="Owner" value={edit.owner} onChange={(v) => patch("owner", v)} options={personOptions} /><SelectField label="Department" value={edit.dept} onChange={(v) => patch("dept", v)} options={deptOptions} /><Field label="Notes" value={edit.notesText} textarea onChange={(v) => patch("notesText", v)} /></>}
      {drawer.type === "staff" && <><Field label="Name" value={edit.name} onChange={(v) => patch("name", v)} /><SelectField label="Role" value={edit.role} onChange={(v) => patch("role", v)} options={roles} /><SelectField label="Access level" value={edit.accessLevel || "crew"} onChange={(v) => patch("accessLevel", v)} options={["company_admin", "manager", "crew_lead", "crew"]} /><SelectField label="Crew" value={edit.crew} onChange={(v) => patch("crew", v)} options={crewOptions} /><SelectField label="Department" value={edit.dept} onChange={(v) => patch("dept", v)} options={deptOptions} /><SelectField label="Status" value={edit.status} onChange={(v) => patch("status", v)} options={["Active", "Inactive", "Available"]} /><Field label="Available" value={edit.available} onChange={(v) => patch("available", v)} /><Field label="Phone" value={edit.phone ?? ""} onChange={patchStaffPhone} /><Field label="Personal PIN" value={edit.pin ?? edit.tempPin ?? ""} onChange={(v) => { patch("pin", v); patch("tempPin", v); }} /><Field label="Temporary / current password" value={edit.password ?? ""} onChange={(v) => patch("password", v)} /><label className="ff-check-row"><input type="checkbox" checked={!!edit.mustChangePassword} onChange={(e) => patch("mustChangePassword", e.target.checked)} /> Force password change on next login</label><div className="ff-permission-grid">{permissions.map(([key, label]) => <label key={key} className="ff-permission-pill"><input type="checkbox" checked={(edit.permissions || []).includes(key)} onChange={() => togglePerm(key)} /> {label}</label>)}</div></>}
      {drawer.type === "message" && <><Field label="Title" value={edit.title} onChange={(v) => { patch("title", v); patch("name", v); }} /><SelectField label="Audience" value={edit.audience || "All"} onChange={(v) => patch("audience", v)} options={["All", "Managers", "Crew Leads", "Crew"]} /><SelectField label="Author" value={edit.author} onChange={(v) => patch("author", v)} options={personOptions} /><Field label="Message" value={edit.body} textarea onChange={(v) => { patch("body", v); patch("note", v); }} /><label className="ff-check-row"><input type="checkbox" checked={!!edit.pinned} onChange={(e) => patch("pinned", e.target.checked)} /> Pin this message</label></>}
      {(drawer.type === "request" || drawer.type === "checkout") && <><SelectField label="Job" value={edit.jobId || ""} onChange={(v) => { const j = board.jobs.find((x:any)=>x.id===v); patch("jobId", v); patch("jobName", j?.name || ""); }} options={["", ...board.jobs.map((j:any)=>j.id)]} /><SelectField label="Person" value={edit.requestedBy || edit.person} onChange={(v) => { patch("requestedBy", v); patch("person", v); }} options={personOptions} /><SelectField label="Crew" value={edit.crew} onChange={(v) => patch("crew", v)} options={crewOptions} /><SelectField label="Status" value={edit.status} onChange={(v) => patch("status", v)} options={drawer.type === "request" ? ["Pending", "Approved", "Denied", "Completed"] : ["Checked Out", "Checked In"]} /><Field label="Start date" type="date" value={edit.startDate || today()} onChange={(v) => patch("startDate", v)} /><Field label="Return / end date" type="date" value={edit.endDate || today()} onChange={(v) => patch("endDate", v)} /><div className="ff-edit-field"><span>Exact tools/equipment</span><div className="ff-asset-picklist">{assets.map((a:any) => <label key={a.id} className="ff-permission-pill"><input type="checkbox" checked={(edit.assetIds || []).includes(a.id)} onChange={() => toggleAsset(a.id)} /> {assetLabel(a)}</label>)}</div></div><Field label="Item summary" value={edit.item} onChange={(v) => patch("item", v)} /><Field label="Note" value={edit.note} textarea onChange={(v) => patch("note", v)} />{drawer.type === "request" && <div className="ff-request-actions"><Button onClick={() => updateRequest(edit.id, "Approved")}><CheckCircle2 /> Approve + Checkout</Button><Button variant="secondary" onClick={() => updateRequest(edit.id, "Completed")}>Complete</Button><Button variant="danger" onClick={() => updateRequest(edit.id, "Denied")}>Deny</Button></div>}</>}
      <div className="ff-drawer-actions"><Button onClick={saveEdit}><Save /> Save</Button>{drawer.mode === "edit" ? <Button variant="danger" onClick={deleteItem}><Trash2 /> Delete</Button> : null}</div>
    </div> : null}</div></aside>
  </main>;
}
